name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Primeiro job: Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: build-develop
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Defina a versão do Node.js que você usa

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

  # Segundo job: ESLint
  lint:
    runs-on: ubuntu-latest
    needs: build  # Este job só roda depois do build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Eslint-develop
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Terceiro job: Testes
  test:
    runs-on: ubuntu-latest
    needs: lint  # Este job só roda depois do ESLint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test-develop
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
